# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/curti/OneDrive/Documents/UIUC/ECE-385/lab5-123/ECE385/lab5.2/lab5.2.srcs/constrs_1/imports/pin_assignment/top.xdc

# IP: C:/Users/curti/OneDrive/Documents/UIUC/ECE-385/lab5-123/ECE385/lab5.2/lab5.2.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet
