# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/curti/OneDrive/Documents/UIUC/Duplicate/ECE-385/Vivado_Projects/Final_Project/lab_6.srcs/sources_1/ip/arrow_right_rom/arrow_right_rom.xci
# IP: The module: 'arrow_right_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/curti/OneDrive/Documents/UIUC/Duplicate/ECE-385/Vivado_Projects/Final_Project/lab_6.gen/sources_1/ip/arrow_right_rom/arrow_right_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arrow_right_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/curti/OneDrive/Documents/UIUC/Duplicate/ECE-385/Vivado_Projects/Final_Project/lab_6.srcs/sources_1/ip/arrow_right_rom/arrow_right_rom.xci
# IP: The module: 'arrow_right_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/curti/OneDrive/Documents/UIUC/Duplicate/ECE-385/Vivado_Projects/Final_Project/lab_6.gen/sources_1/ip/arrow_right_rom/arrow_right_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arrow_right_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
